namespace DeclareAPI.Agent.Core.Models;

/// <summary>
/// Represents a field/column in an entity.
/// </summary>
public class Field
{
    /// <summary>
    /// Field name (e.g., "id", "email", "created_at").
    /// </summary>
    public string Name { get; set; } = "";

    /// <summary>
    /// Data type (e.g., "uuid", "varchar", "text", "integer", "timestamp").
    /// </summary>
    public string Type { get; set; } = "";

    /// <summary>
    /// Whether the field allows NULL values.
    /// </summary>
    public bool IsNullable { get; set; } = true;

    /// <summary>
    /// Whether this field is a primary key.
    /// </summary>
    public bool IsPrimaryKey { get; set; }

    /// <summary>
    /// Whether this field has a unique constraint.
    /// </summary>
    public bool IsUnique { get; set; }

    /// <summary>
    /// Whether this field is a foreign key.
    /// </summary>
    public bool IsForeignKey { get; set; }

    /// <summary>
    /// The referenced table for foreign keys.
    /// </summary>
    public string? ForeignKeyTable { get; set; }

    /// <summary>
    /// The referenced column for foreign keys (defaults to "id").
    /// </summary>
    public string? ForeignKeyColumn { get; set; }

    /// <summary>
    /// Optional description/comment for the field.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Maximum length for string types (varchar).
    /// </summary>
    public int? MaxLength { get; set; }

    /// <summary>
    /// Default value expression (e.g., "gen_random_uuid()", "NOW()").
    /// </summary>
    public string? DefaultValue { get; set; }

    /// <summary>
    /// Whether this field should be auto-generated (e.g., UUID, auto-increment).
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    public override string ToString() => $"{Name} ({Type}){(IsPrimaryKey ? " PK" : "")}{(IsForeignKey ? " FK" : "")}{(IsUnique ? " UK" : "")}";
}
