<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DeclareAPI.Agent.Parsers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeclareAPI.Agent.Core\DeclareAPI.Agent.Core.csproj" />
  </ItemGroup>

</Project>
